### ISSUE TITLE
bonfire.link domain name is blocked on Facebook

### ISSUE THREAD

**Issue by OmeGak** [bonfirelink/infrastructure#3]
Not like we are dying to post on Facebook, but being blocked means that we cannot share links to the website or the TV on Messenger.

|oh noes!!!|
|:-|
|![image](https://user-images.githubusercontent.com/716307/82666907-210f3300-9c37-11ea-9d5e-015c6fad7471.png)|

The domain name has been blocked from the first day. At first, we thought it was sheer repression and that we should just remind them that we are _not a cult_, but it's seems that Facebook blocking pages arbitrarily [is not something terribly rare](https://johnfowler.co/facebook-blocked-my-website/). We are certainly not violating their [Community Standards](https://www.facebook.com/communitystandards/introduction), so, what can we do?

Unfortunately, there is no guaranteed method to get the domain name unblocked. Not even to reach Facebook. So our only chance is to report via different means and accounts that there is a mistake in their blocking of https://bonfire.link.

What we can do is trying to share the link on Facebook or Messenger and click on _"let us know"_. If you don't feel madly inspired, feel free to copy&paste this:

> Hi there, Facebook! A website I am trying to share (https://bonfire.link) is blocked for some reason. I have read the entire Facebook Community Standards and I don't see anything this website is violating. It seems to me this is a mistake. It would be great if you could review it. Thanks in advance!

---

As per this guide, there are two other options: 1) trying to run a ad campaign on Facebook and 2) use a service like [Unblock My Website](https://unblockmywebsite.com/). But I don't think we need this so desperately as to pay money for.

**Comment by TrizML** [comment]
How this status on this? Maybe we could contact Heather, I know she knows how to handle this things.

**Comment by OmeGak** [comment]
> How is status on this?

No update. I sent a report and received no answer.

> It's only when I click on the link that I go to the Community Standards page but I don't see where to tell them that our page doesn't go against those standards.

Facebook is extremely opaque as to why they block sites. You can read more about it here: https://johnfowler.co/facebook-blocked-my-website/.

**Comment by OmeGak** [comment]
I did nothing but this is now fixed. ¯\\\_(ツ)\_/¯
